// <auto-generated />
using System;
using APIFaunaEnriquillo.InfrastructureLayer.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFaunaEnriquillo.InfraestructureLayer.Persistence.Migrations
{
    [DbContext(typeof(FaunaDbContext))]
    [Migration("20250526210936_InitBD")]
    partial class InitBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Animal", b =>
                {
                    b.Property<Guid?>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dieta")
                        .HasColumnType("int");

                    b.Property<string>("DistribucionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoDeConservacion")
                        .HasColumnType("int");

                    b.Property<int>("EstatusBiogeográfico")
                        .HasColumnType("int");

                    b.Property<string>("Familia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Filo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FormaDeReproduccion")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("HabitatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCientifico")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreComun")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Orden")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubEspecie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoDesarrolloEmbrionario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAnimal")
                        .HasName("PKAnimal");

                    b.HasIndex("HabitatId");

                    b.ToTable("Animales", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Habitat", b =>
                {
                    b.Property<Guid?>("IdHabitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clima")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCientifico")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreComun")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UbicacionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdHabitat")
                        .HasName("PKHabitat");

                    b.ToTable("Habitats", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Planta", b =>
                {
                    b.Property<Guid?>("IdPlanta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clase")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistribucionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstadoDeConservacion")
                        .HasColumnType("int");

                    b.Property<int>("EstatusBiogeografico")
                        .HasColumnType("int");

                    b.Property<string>("Familia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Filo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genero")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("HabitatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCientifico")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreComun")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Orden")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubEspecie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPlanta")
                        .HasName("PKPlanta");

                    b.HasIndex("HabitatId");

                    b.ToTable("Plantas", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Animal", b =>
                {
                    b.HasOne("APIFaunaEnriquillo.Core.DomainLayer.Models.Habitat", "Habitat")
                        .WithMany("Animales")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Habitat");
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Planta", b =>
                {
                    b.HasOne("APIFaunaEnriquillo.Core.DomainLayer.Models.Habitat", "Habitat")
                        .WithMany("Plantas")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Habitat");
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Models.Habitat", b =>
                {
                    b.Navigation("Animales");

                    b.Navigation("Plantas");
                });
#pragma warning restore 612, 618
        }
    }
}
