// <auto-generated />
using System;
using APIFaunaEnriquillo.InfrastructureLayer.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFaunaEnriquillo.InfraestructureLayer.Persistence.Migrations
{
    [DbContext(typeof(FaunaDbContext))]
    [Migration("20250604044851_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Animal", b =>
                {
                    b.Property<Guid?>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dieta")
                        .HasColumnType("int");

                    b.Property<string>("DistribucionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoDeConservacion")
                        .HasColumnType("int");

                    b.Property<int>("EstatusBiogeográfico")
                        .HasColumnType("int");

                    b.Property<int>("FormaDeReproduccion")
                        .HasColumnType("int");

                    b.Property<Guid?>("HabitatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("TipoDesarrolloEmbrionario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAnimal")
                        .HasName("PKAnimal");

                    b.HasIndex("HabitatId");

                    b.ToTable("Animales", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Habitat", b =>
                {
                    b.Property<Guid?>("IdHabitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clima")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdHabitat")
                        .HasName("PKHabitat");

                    b.ToTable("Habitats", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Planta", b =>
                {
                    b.Property<Guid?>("IdPlanta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistribucionGeograficaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoDeConservacion")
                        .HasColumnType("int");

                    b.Property<int>("EstatusBiogeografico")
                        .HasColumnType("int");

                    b.Property<Guid?>("HabitatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPlanta")
                        .HasName("PKPlanta");

                    b.HasIndex("HabitatId");

                    b.ToTable("Plantas", (string)null);
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Animal", b =>
                {
                    b.HasOne("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Habitat", "Habitat")
                        .WithMany("Animales")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.ClaseAnimal", "Clase", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("ClaseAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.EspecieAnimal", "Especie", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("EspecieAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.FamiliaAnimal", "Familia", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FamiliaAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.FiloAnimal", "Filo", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("FiloAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.GeneroAnimal", "Genero", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneroAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.NombreCientificoAnimal", "NombreCientifico", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreCientificoAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.NombreComunAnimal", "NombreComun", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreComunAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.OrdenAnimal", "Orden", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("OrdenAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.AnimalObjects.SubEspecieAnimal", "SubEspecie", b1 =>
                        {
                            b1.Property<Guid>("AnimalIdAnimal")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SubEspecieAnimal");

                            b1.HasKey("AnimalIdAnimal");

                            b1.ToTable("Animales");

                            b1.WithOwner()
                                .HasForeignKey("AnimalIdAnimal");
                        });

                    b.Navigation("Clase")
                        .IsRequired();

                    b.Navigation("Especie")
                        .IsRequired();

                    b.Navigation("Familia")
                        .IsRequired();

                    b.Navigation("Filo")
                        .IsRequired();

                    b.Navigation("Genero")
                        .IsRequired();

                    b.Navigation("Habitat");

                    b.Navigation("NombreCientifico")
                        .IsRequired();

                    b.Navigation("NombreComun")
                        .IsRequired();

                    b.Navigation("Orden")
                        .IsRequired();

                    b.Navigation("SubEspecie")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Habitat", b =>
                {
                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.HabitatObjects.NombreCientificoHabitat", "NombreCientifico", b1 =>
                        {
                            b1.Property<Guid>("HabitatIdHabitat")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreCientificoHabitat");

                            b1.HasKey("HabitatIdHabitat");

                            b1.ToTable("Habitats");

                            b1.WithOwner()
                                .HasForeignKey("HabitatIdHabitat");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.HabitatObjects.NombreComunHabitat", "NombreComun", b1 =>
                        {
                            b1.Property<Guid>("HabitatIdHabitat")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreComunHabitat");

                            b1.HasKey("HabitatIdHabitat");

                            b1.ToTable("Habitats");

                            b1.WithOwner()
                                .HasForeignKey("HabitatIdHabitat");
                        });

                    b.Navigation("NombreCientifico")
                        .IsRequired();

                    b.Navigation("NombreComun")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Planta", b =>
                {
                    b.HasOne("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Habitat", "Habitat")
                        .WithMany("Plantas")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.ClasePlant", "Clase", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ClasePlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.EspeciePlant", "Especie", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EspeciePlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.FamiliaPlant", "Familia", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FamiliaPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.FiloPlant", "Filo", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FiloPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.GeneroPlant", "Genero", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("GeneroPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.NombreCientificoPlant", "NombreCientifico", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreCientificoPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.NombreComunPlant", "NombreComun", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("NombreComunPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.OrdenPlant", "Orden", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("OrdenPlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.OwnsOne("APIFaunaEnriquillo.Core.DomainLayer.Value_object.PlantObjects.SubEspeciePlant", "SubEspecie", b1 =>
                        {
                            b1.Property<Guid>("PlantaIdPlanta")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SubEspeciePlanta");

                            b1.HasKey("PlantaIdPlanta");

                            b1.ToTable("Plantas");

                            b1.WithOwner()
                                .HasForeignKey("PlantaIdPlanta");
                        });

                    b.Navigation("Clase")
                        .IsRequired();

                    b.Navigation("Especie")
                        .IsRequired();

                    b.Navigation("Familia")
                        .IsRequired();

                    b.Navigation("Filo")
                        .IsRequired();

                    b.Navigation("Genero")
                        .IsRequired();

                    b.Navigation("Habitat");

                    b.Navigation("NombreCientifico")
                        .IsRequired();

                    b.Navigation("NombreComun")
                        .IsRequired();

                    b.Navigation("Orden")
                        .IsRequired();

                    b.Navigation("SubEspecie")
                        .IsRequired();
                });

            modelBuilder.Entity("APIFaunaEnriquillo.Core.DomainLayer.Agregate.HabitatAgregate.Habitat", b =>
                {
                    b.Navigation("Animales");

                    b.Navigation("Plantas");
                });
#pragma warning restore 612, 618
        }
    }
}
